import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Typed from 'typed.js'
import React, { useRef, useState } from 'react'


export default function Home() {

  const [isLoading, setIsLoading] = useState(false);

  const [responseTexts, setResponseTexts] = useState([]);

  const [isInputVisible, setIsInputVisible] = useState(false);

  const typedRef = useRef(null)

  const newDivRef = useRef(null);

  const textareaRef = useRef(null);


  function handleClick() {

    const value = textareaRef.current.value;

    if (!value) {
      alert('请输入内容')
      return false
    }

    setIsLoading(true);
    setIsInputVisible(true)

    fetch('http://spdhapi.cyshkj.cn/test?text=' + value)
      .then(response => response.json())
      .then(res => {
        // 处理接口返回的数据
        console.log(res.data)
        // 显示打印的div
        const typed = new Typed(typedRef.current, {
          strings: [res.data],
          typeSpeed: 10,
          showCursor: false,
          backDelay: 100,
          onComplete: () => {
            // 关闭打印文本
            setIsInputVisible(false)
            // 按钮可点击
            setIsLoading(false);

            // 显示文本在div内
            setResponseTexts(prevResponseTexts => [res.data, ...prevResponseTexts])

            // 清空输入框
            // textareaRef.current.value = '';

            // 销毁这个对象
            typed.destroy()


            // 页面上显示调用次数-1


          },
        });
      })
      .catch(error => {
        console.error(error);
        setIsLoading(false);
      });
  }

  return (
    <>
      <Head>
        <title>智聊</title>
        <meta name="description" content="Generated by Test" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        {/* 顶部介绍 */}
        <div className={styles.header}>
          Hello,World!
        </div>
        {/* 问答区域 */}
        <div className={styles.c_input_box}>
          <textarea ref={textareaRef} className={styles.c_input} rows={4} placeholder='在这里输入你的问题吧~' />
        </div>
        <div className={styles.btn_box}>
          <button className={styles.btn} onClick={handleClick} disabled={isLoading} >{isLoading ? '加载中...' : '获取数据'}</button>
        </div>
        {/* 结果区域 */}
        <div className={styles.answer_box} ref={newDivRef}>

          {isInputVisible && <div ref={typedRef} className={styles.answer}></div>}

          {responseTexts.map((responseText, index) => (
            <div key={index} className={styles.answer}>{responseText}</div>
          ))}

        </div>

        {/* 尾部 */}
      </main>

    </>
  );
}
